version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-db
    environment:
      MONGO_INITDB_DATABASE: webApp
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pollat@233
    ports:
      - "27018:27017"
    volumes:
      - smt-v1-volume:/data/db
      #- $PWD/mongo-init/init.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  smt-v1-volume:
    name: smt-v1-data